### ISSUE TITLE
Make a Contract from Scratch : How to write compile script : How to write Test Cases : How to write Deploy Script

### ISSUE THREAD

**Issue by humanwhoexplores** [humanwhoexplores/smart-contracts#8]

**Comment by humanwhoexplores** [comment]
Use this BoilerPlate zip :  Most importantly it gives us 'package.json' and the folder structure for our smart contract
[boilerplate-inbox.zip](https://github.com/humanwhoexplores/smart-contracts/files/7182959/boilerplate-inbox.zip)

**Comment by humanwhoexplores** [comment]
1.) Unzip 
2.) use  "nvm use 12.14.1"
3.) npm install
Now install Solidity 
4.) npm install --save solc

**Comment by humanwhoexplores** [comment]
The project Directory Structure looks like 
![Uploading Screenshot 2021-09-17 at 11.25.01 AM.png…]()

**Comment by humanwhoexplores** [comment]
<img width="341" alt="Screenshot 2021-09-17 at 11 25 01 AM" src="https://user-images.githubusercontent.com/9106754/133732579-68ada5e4-e6c1-42b4-a1b3-bbb44d44d908.png">

This is the Project's Directory Structure

**Comment by humanwhoexplores** [comment]
- The Contracts are stored in contracts directory 
- The Test cases are written in test/. directory 
- package.josn : stores metadata of libraries - dependencies
- compile.js :  compilation script
- deploy.js :  deployment script

**Comment by humanwhoexplores** [comment]
Show some light on the Compilation Process 
<img width="616" alt="Screenshot 2021-09-17 at 11 37 00 AM" src="https://user-images.githubusercontent.com/9106754/133732882-c3678d4d-dff4-4854-bce6-16c06a0133d7.png">

**Comment by humanwhoexplores** [comment]
The **Solidity Compiler** spits out 2 entities 

- Contract Bytecode : This is the bytecode that is deployed on the Test Network / Main Network
- Application Binary Interface(ABI) :- Javascript Interpretation layer over the contract . ex. Web3 library uses ABI to :-   interact with contract.

**Comment by humanwhoexplores** [comment]
`javascript
const path = require("path");
const fs = require("fs");
const solc = require("solc");

const inboxPath = path.resolve(__dirname, "contracts", "Inbox.sol");
const source = fs.readFileSync(inboxPath, "utf8");

console.log(solc.compile(source, 1));
`

This is the compile Script.

**Comment by humanwhoexplores** [comment]
**How to test the Contract Locally !!!**

<img width="558" alt="Screenshot 2021-09-17 at 11 57 43 AM" src="https://user-images.githubusercontent.com/9106754/133735266-4c040cb3-5e8b-4484-a874-67c59c8dd073.png">

**Comment by humanwhoexplores** [comment]
I will deploy the contract , i will deploy the contract on **Ganache** also called as **TestRPC**  
It is a Test Network that runs locally on the machine.

**Comment by humanwhoexplores** [comment]
Now compile the contract by hitting 
**node compile.js**

**Comment by humanwhoexplores** [comment]
Now i want to run the tests 
I am running this command 

 npm install --save mocha ganache-cli web3@1.0.0-beta.26
 
 This installs :-   Mocha :  the library to run tests
Ganache-cli :  the local test network
Web3 :- for ABI functions

**Comment by humanwhoexplores** [comment]
notes on Web3 Versioning 

<img width="811" alt="Screenshot 2021-09-17 at 12 33 16 PM" src="https://user-images.githubusercontent.com/9106754/133739232-77695a0d-5025-427a-950a-6016903c1bf0.png">

**Comment by humanwhoexplores** [comment]
`const assert = require("assert");
const ganache = require("ganache-cli");
const Web3 = require("web3");
const web3 = new Web3(ganache.provider());
const { interface, bytecode } = require("../compile");

let accounts;
let inbox;

beforeEach(async () => {
  // Get a list of all accounts
  accounts = await web3.eth.getAccounts();
  inbox = await new web3.eth.Contract(JSON.parse(interface))
    .deploy({
      data: bytecode,
      arguments: ["Hi there!"],
    })
    .send({ from: accounts[0], gas: "1000000" });
});

describe("Inbox", () => {
  it("deploys a contract", () => {
    console.log(inbox);
  });
});
`

this is the complete Test case file : 

$ npm run test 
this FAILS AT 

`  Inbox
    1) "before each" hook for "deploys a contract"


  0 passing (72ms)
  1 failing

  1) "before each" hook for "deploys a contract":
     SyntaxError: Unexpected token u in JSON at position 0
      at JSON.parse (<anonymous>)
      at Context.<anonymous> (test/Inbox.test.js:13:44)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the inbox@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krchopra/.npm/_logs/2021-09-17T08_31_26_389Z-debug.log`

**Comment by humanwhoexplores** [comment]
This works as a charm 
https://github.com/humanwhoexplores/smart-contracts/tree/main/inbox
